apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: docker.io/luukio/u2net-bg-removal
    docker:
      dockerfile: ./Dockerfile
deploy:
  kubectl:
    manifests:
      - deploy/service.yaml
